# Generated by Django 4.2.2 on 2023-07-30 17:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lfmsh.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID аккаунта.', primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='Not stated', max_length=40, verbose_name='Имя:')),
                ('middle_name', models.CharField(default='Not stated', max_length=40, verbose_name='Отчество:')),
                ('last_name', models.CharField(default='Not stated', max_length=40, verbose_name='Фамилия:')),
                ('party', models.IntegerField(default=0, verbose_name='Отряд:')),
                ('account_status', models.CharField(blank=True, default='', max_length=100, verbose_name='Статус:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь:')),
            ],
            options={
                'ordering': ['party', 'last_name'],
                'permissions': (('staff_', 'Принадлежность к персоналу'), ('register', 'Может регистрировать пользователей'), ('edit_users', 'Может изменять пользователей'), ('ant_edit', 'Может принимать заявки')),
            },
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('cnt', models.IntegerField(default=1, editable=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название чата:')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Описание чата:')),
                ('anonim', models.BooleanField(default=False, verbose_name='Если вы хотите сделать чат анонимным, поставьте здесь галочку. Этот параметр неизменяем.')),
                ('anonim_legacy', models.BooleanField(default=False, verbose_name='Поставьте галочку, если хотите разрешить участникам отправлять анонимные сообщения.')),
                ('chat_ico', models.ImageField(null=True, upload_to='', verbose_name='Иконка чата:')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID чата.', primary_key=True, serialize=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_chat', to='lfmsh.account', verbose_name='Создатель:')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('date', models.DateField(verbose_name='Дата:')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='Время:')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст:')),
                ('anonim', models.BooleanField(default=False, verbose_name='Если вы хотите отправить это сообщение анонимно, поставьте здесь галочку.')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID сообщения.', primary_key=True, serialize=False)),
                ('anonim_legacy', models.BooleanField(default=False, editable=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_mess', to='lfmsh.account', verbose_name='Отправитель:')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_mess', to='lfmsh.chat', verbose_name='Получатель:')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='chat_valid',
            fields=[
                ('avaliable', models.BooleanField(default=True, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID.', primary_key=True, serialize=False)),
                ('list_members', lfmsh.models.ListField(default=[], help_text='Список ID участников:', null=True)),
                ('list_messages', lfmsh.models.ListField(default=[], help_text='Список ID сообщений:', null=True)),
                ('what_chat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfmsh.chat', verbose_name='Чат:')),
            ],
        ),
        migrations.CreateModel(
            name='chat_and_acc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID.', primary_key=True, serialize=False)),
                ('readen', models.BooleanField(default=False, editable=False)),
                ('what_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfmsh.account', verbose_name='Аккаунт:')),
                ('what_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfmsh.chat', verbose_name='Чат:')),
            ],
        ),
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('number', models.IntegerField(default=0, verbose_name='Номер в списке:')),
                ('name', models.TextField(max_length=50, verbose_name='Название:')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст:')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID.', primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, verbose_name='Объявление принято?')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='Картинка:')),
                ('orientation', models.IntegerField(choices=[(0, 'Горизонтально'), (1, 'Вертикально'), (2, 'Квадрат')], default=0, verbose_name='Ориентация:')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfmsh.account', verbose_name='Отправитель:')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
