# Generated by Django 4.2.2 on 2023-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название темы:')),
                ('type_theme', models.CharField(choices=[('def', 'Базовый'), ('com', 'Компьютерный'), ('fon', 'Телефонный')], default=0, max_length=3, verbose_name='Тип темы:')),
            ],
        ),
    ]
