# Generated by Django 4.2.2 on 2023-07-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_answer',
        ),
        migrations.DeleteModel(
            name='rools',
        ),
        migrations.DeleteModel(
            name='shop',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['party', 'last_name'], 'permissions': (('staff_', 'Принадлежность к персоналу'), ('register', 'Может регистрировать пользователей'), ('edit_users', 'Может изменять пользователей'), ('meria', 'Мэрия в банке'))},
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_group',
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
