# Generated by Django 4.2.2 on 2023-07-25 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0002_delete_daily_answer_delete_rools_delete_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('number', models.IntegerField(default=0, verbose_name='Номер в списке:')),
                ('name', models.TextField(max_length=200, verbose_name='Название:')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст:')),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID.', primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False, verbose_name='Объявление принято?')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lfmsh.account', verbose_name='Отправитель:')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
    ]
