# Generated by Django 4.2.2 on 2023-08-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0002_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='type_theme',
            field=models.CharField(choices=[('d', 'Базовый'), ('c', 'Компьютерный'), ('f', 'Телефонный')], default=0, max_length=1, verbose_name='Тип темы:'),
        ),
    ]
