# Generated by Django 4.2.2 on 2023-08-02 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0003_alter_theme_type_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Тема активна?'),
        ),
        migrations.AddField(
            model_name='theme',
            name='postfix',
            field=models.CharField(default='', help_text='Постфикс - это то, что будет приписано в конец css тэга.', max_length=15, verbose_name='Постфикс:'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID.', primary_key=True, serialize=False),
        ),
    ]
