# Generated by Django 4.2.2 on 2023-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0003_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['party', 'last_name'], 'permissions': (('staff_', 'Принадлежность к персоналу'), ('register', 'Может регистрировать пользователей'), ('edit_users', 'Может изменять пользователей'), ('meria', 'Может менять некоторые данные'), ('ant_edit', 'Может принимать заявки'))},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Название:'),
        ),
    ]
