# Generated by Django 4.2.2 on 2023-07-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0004_alter_account_options_alter_announcement_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='plan',
        ),
    ]
