# Generated by Django 4.2.2 on 2023-08-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0004_theme_is_active_theme_postfix_alter_theme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='type_theme',
            field=models.CharField(choices=[('c', 'Компьютерный'), ('f', 'Телефонный')], default=0, max_length=1, verbose_name='Тип темы:'),
        ),
    ]
