# Generated by Django 4.2.2 on 2023-07-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0005_delete_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['party', 'last_name'], 'permissions': (('staff_', 'Принадлежность к персоналу'), ('register', 'Может регистрировать пользователей'), ('edit_users', 'Может изменять пользователей'), ('ant_edit', 'Может принимать заявки'))},
        ),
    ]
