# Generated by Django 4.2.2 on 2023-08-02 13:36

from django.db import migrations, models
import django.db.models.deletion
import lfmsh.models


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0005_alter_theme_type_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='is_active',
        ),
        migrations.AddField(
            model_name='account',
            name='theme_self',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lfmsh.theme', verbose_name='Тема аккаунта:'),
        ),
        migrations.AddField(
            model_name='theme',
            name='accs',
            field=lfmsh.models.ListField(default=[], help_text='Список ID аккаунтов с данной темой:', null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='postfix',
            field=models.CharField(default='', help_text='Постфикс - это то, что будет приписано в конец css тэга. Писать только латиницей.\nПример: тэг "pass". Тогда к css при генерации таблицы будет обращён запрос "table_pass".', max_length=15, verbose_name='Постфикс:'),
        ),
    ]
