# Generated by Django 4.2.2 on 2023-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0006_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_ico',
            field=models.ImageField(null=True, upload_to='', verbose_name='Иконка чата:'),
        ),
    ]
