# Generated by Django 4.2.2 on 2023-08-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0006_remove_theme_is_active_account_theme_self_theme_accs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='accs',
        ),
    ]
