# Generated by Django 4.2.2 on 2023-08-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lfmsh', '0007_remove_theme_accs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='theme_self',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lfmsh.theme', verbose_name='Тема аккаунта:'),
        ),
    ]
